[package]
name = "grrs"
version = "0.1.0"
edition = "2018"


[dependencies]
structopt = "0.3.25"
anyhow = "1.0.44"
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"